name: Deploy to Playstore beta

on:
  workflow_dispatch:

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Configure Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > app/release.keystore
          echo "storeFile=release.keystore" > keystore.properties
          echo "keyAlias=$KEY_ALIAS" >> keystore.properties
          echo "storePassword=$KEYSTORE_PASSWORD" >> keystore.properties
          echo "keyPassword=$KEY_PASSWORD" >> keystore.properties
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Create Google Play Config file
        run: echo "$GOOGLE_PLAY_JSON" | base64 -d > play_config.json
        env:
          GOOGLE_PLAY_JSON: ${{ secrets.GOOGLE_PLAY_JSON }}

      - name: Deploy to Beta track
        run: bundle exec fastlane beta
